version: "3"
services:
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: pytorch
    volumes:
      - ./:/usr/src
    ports:
      - "8888:8888"
    runtime: nvidia
    environment:
      - "TZ=Japan"
    working_dir: /usr/src/source
    tty: true